### ISSUE TITLE
'DRY' up or abstract the initialization of the buttons / handlers for different algorithms

### ISSUE THREAD

**Issue by palecrow** [walter298/Algorithm-Master#13]
Right now, each algorithm has repetitive code that establishes many similar things precisely the same way.

Using the principles of DRY (Don't Repeat Yourself), find a way to clean up code so you don't simply cut and paste code snippets for each new algorithm.  Copy and Paste is a bad way to code because it causes the likelihood of changes not being applied equally to all cases of similar implementations, among other problems.

Consider how you can abstract the various algorithms, and how using an Interface may help.

**Comment by walter298** [comment]
I made all the buttons have a single factory function that sizes them and creates an AlgorithmPage object when they are clicked
