### ISSUE TITLE
Make numeric entry more user-friendly

### ISSUE THREAD

**Issue by palecrow** [walter298/Algorithm-Master#23]
The current behavior for the numeric inputs is:

- Initializes with a textual entry - not a placeholder but actual selectable text.  This means the user needs to manually erase the contents in order to add valid numbers.  This is a design antipattern. The expected pattern would be to use a text area placeholder (if available) which clears upon user focus.  This is likely a property that can be set for the input field.
- Requires entry using space separation. There are a couple of problems here.  One is that this is not intuitive - you have to 'read the directions' in order to know that only spaces are allowed.  And currently, the directions are erased the moment you start using it, so if you try to enter something, there is no way to know why it's wrong.  Finally, the input parsing is not intelligent in that if someone enters two spaces between numbers, this will throw an error. A standard pattern of expectation here is to allow a set of non-numerics, e.g. space and comma, and to consider any such block of these as a delimiter, not individual characters.  This is usually achieved by regular expression processing.

**Comment by palecrow** [comment]
Note, there is a property you can set that provides the placheholder effect in a TextField.

**Comment by walter298** [comment]
The Textfield is no longer initialized with the placeholder text. Instead, the placeholder is grayed out. The user can also use any separator they want between numbers, not just spaces (I did in fact use a regular expression to achieve this).
