### ISSUE TITLE
Allow ability to reset execution (or just open up form for re-execution)

### ISSUE THREAD

**Issue by palecrow** [walter298/Algorithm-Master#24]
Currently, after running an algorithm with a set of numbers, you cannot try a different set with the same algorithm.  The execute button is disabled. Ideally, the button is simply re-enabled after the algorithm animation is complete.

**Comment by walter298** [comment]
The execute button now only disables while the numbers are moving. Once the numbers stop moving, you can click execute again with the a new set of numbers.
