### ISSUE TITLE
Discuss possible over-use of 'var'

### ISSUE THREAD

**Issue by palecrow** [walter298/Algorithm-Master#9]
In many of the files, 'var' is used to declare variables. This may be a matter of personal preference, but 'var' is a vague and loose way to declare variables when Java is fairly type-strict. As a rule of thumb, it may be more appropriate to simply declare the actual type, for example:

Instead of:
`var selectionSortButton = new Button("Selection Sort");`

Use:
`Button selectionSortButton = new Button("Selection Sort");`

This not only makes it clear visually what the type is, but also reinforces that this cannot be reassigned to any other type.

**Comment by walter298** [comment]
We're always forced to declare the correct type of the variable on the right side when we say var x = new Foo(), so putting the type on the left side as well is redundant and not DRY-compliant, especially when Java library authors can be merciless in how long they make their class names.
